### ISSUE TITLE
Error: Internal error: unknown identifier undefined

### ISSUE THREAD

**Issue by Vbboi24** [gund/ng-dynamic-component#377] opened 2020-07-02 18:12 UTC
Hello @gund ,

Thanks for this awesome library,

But i am having a problem in importing this as part of my Angular 9 Project.
I explored the issues and i used npm i ng-dynamic-component@6.1.1-no-barrels.1 to avoid the pinned issue.
But yet still, I am quite stuck with this error during ng serve of my app.

Can you please try helping me out here ?

**Comment by gund** [comment] 2020-07-03 09:15
Hi, unfortunately I cannot help without an minimal online reproduction example. Could you create one please?

**Comment by Vbboi24** [comment] 2020-07-03 09:19
Hey @gund ,

Thanks for the reply. Sure, Let me please try creating a stackblitz and revert back

**Comment by konuch** [comment] 2020-08-07 06:54
> Hey @gund ,
> 
> Thanks for the reply. Sure, Let me please try creating a stackblitz and revert back

Do you have Ivy build enabled in your tsConfig file?

**Comment by gund** [comment] 2020-08-07 08:46
@konuch I do not think it matters as the library can be compiled by the NGCC to Ivy version.

**Comment by L-X-T** [comment] 2020-09-10 09:27
Same issue. Also using the no-barrels. Problem only occurs when using ng build not on ng serve. We use @nrwl.

**Comment by willyboy** [comment] 2020-10-23 19:53
@gund I provided a reproduction here https://github.com/gund/ng-dynamic-component/issues/408
We are also using @nrwl but I doubt that's the cause because I think ng build bypasses nrwl build commands.

**Comment by willyboy** [comment] 2020-10-23 19:58
@L-X-T do you have ivy disabled? We do and it seems like with Ivy enabled there isn't an issue.

**Comment by gund** [comment] 2022-08-28 01:33
I'm closing this issue as it's outdated.
If you want to reopen the discussion please feel free to open a new issue.

**Closed by gund** 2022-08-28 01:33 UTC
