### ISSUE TITLE
ngOnInit not work when call ndc-dynamic

### ISSUE THREAD

**Issue by viethien** [gund/ng-dynamic-component#234] opened 2019-04-22 05:31 UTC
I use ndc-dynamic component to display Compomnent in list.

Component display well on single page because it call `ngOnInit `but ngOnInit did not trigger in ndc-dynamic.
`<ndc-dynamic class="no-drag" [ndcDynamicComponent]="item.component" (ndcDynamicCreated)="componentCreated($event)"></ndc-dynamic>`

I tried (ndcDynamicCreated)="componentCreated($event)" but it still did not trigger to componentCreated method in Component.
How can I trigger ngOnInit in ng-dynamic-component?

Thanks

**Comment by gund** [comment] 2019-05-16 23:57
Hey @viethien thanks for reporting this.

Actually you are right, if you simply use `ndc-dynamic` component without `ndcDynamicInputs` directive then on init hook will not be called.

I'm not quite sure if on init will be called with that directive now that I've checked the specs...

This is definitely a bug and should be fixed.

**Comment by gund** [comment] 2020-08-16 15:49
Looks like this is not reproducible anymore. See example https://stackblitz.com/edit/angular-ivy-tddmxm?file=src%2Fapp%2Fapp.component.html

If you encounter similar issue feel free to create a new issue.

**Closed by gund** 2020-08-16 15:49 UTC
Labels: bug
