### ISSUE TITLE
@Input is set every time anything changes

### ISSUE THREAD

**Issue by thepian** [gund/ng-dynamic-component#367] opened 2020-04-07 08:43 UTC
It seems that updateInputs sets all inputs regardless of what has changed. If you use a setter for an input it gets called every time anything is changed. Is there a way around this? Or can it be considered a bug?

**Comment by gund** [comment] 2020-04-07 12:47
Thanks for creating an issue.

It would really help if you could create a simple example of the issue on online sandbox (like stackblitz or codesandbox) so I can investigate the cause of this behavior.

**Comment by gund** [comment] 2020-05-22 19:24
A little update on this topic - it seems like Angular's own Change Detection cycle does the same thing - it sets inputs every time CD pass happens even when actual values did not change.

So it seems like the library behaves in the same compatible way.

I would suggest you to stop using setters and always use life-cycle hooks unless your setters are super trivial.

I will close this issue as this is the default befavior in Angular anyways.

**Closed by gund** 2020-05-22 19:24 UTC
