### ISSUE TITLE
Can't get ndcDynamicDirectives to work

### ISSUE THREAD

**Issue by atgillette** [gund/ng-dynamic-component#307] opened 2019-10-02 18:18 UTC
Hi,

I'm trying to use ndcDynamicDirectives to set fxFlex directive for Angular Flex-Layout.  In my component class file, I defining a dirs property like this:

`
dirs: [
              dynamicDirectiveDef(
                FlexDirective,
                {
                  fxFlex: '50%'
                }
              )
            ]
`

And in the component template, I'm using the following code:

`
      <ndc-dynamic *ngFor="let table of tables; trackBy: trackById"
                    [ndcDynamicComponent]="table.component"
                    [ndcDynamicInputs]="table.inputs"
                    [ndcDynamicDirectives]="table.dirs">
      </ndc-dynamic>
`

I'm getting the following error:

`
TypeError: Cannot read property 'map' of undefined
    at DynamicDirectivesDirective.createDirective (ng-dynamic-component.es2015.js:1008)
    at DynamicDirectivesDirective.initDirective (ng-dynamic-component.es2015.js:923)
    at ng-dynamic-component.es2015.js:886
`

Can someone show me how to fix this?

Thx,

Adrian

**Comment by gund** [comment] 2019-10-03 06:32
Hi, it will be good if you could open source code tab in Dev tools where error appeared and make a screenshot - so I can see where it occured.

One possibility is that some table does have `dirs` property as `undefined`...

**Comment by gund** [comment] 2019-10-03 20:25
Duplicate of #278

Please follow that issue for further resolution.

**Closed by gund** 2019-10-03 20:25 UTC

**Comment by atgillette** [comment] 2019-10-03 23:01
hi @gund,

I added `"emitDecoratorMetadata": true,` and it did not help.

**Comment by gund** [comment] 2019-10-04 15:52
This is not going to help as said in https://github.com/gund/ng-dynamic-component/issues/278#issuecomment-534253949

There is currently no workaround for AOT compiled apps.

Please stay tuned in the issue mentioned above.
