### ISSUE TITLE
can't bind to ndcDynamicComponent

### ISSUE THREAD

**Issue by sahyun1** [gund/ng-dynamic-component#63] opened 2017-09-26 03:18 UTC
Hi,

I'm trying to use this but I get the following error
Uncaught (in promise): Error: Template parse errors: Can't bind to 'ndcDynamicComponent' since it isn't a known property of 'ndc-dynamic'.

I've imported this in app.module.ts along with components I'd like to use.
DynamicModule.withComponents([DateAnswerComponent,TextAnswerComponent]).

I'm using it with ionic 3 if that matters. 

could anybody help me with this?

many thanks

**Comment by alandroid** [comment] 2018-03-15 16:13
I am also having this issue: **Can't bind to 'ndcDynamicComponent' since it isn't a known property of ...**

**Comment by gund** [comment] 2018-03-15 16:18
Please can you provide reproduciable live example?

**Comment by alandroid** [comment] 2018-03-15 16:55
Hey @gund i cannot provide live example due to time constrains however, i managed to get it working along with inputs, thank you very much!!

**Comment by gund** [comment] 2018-03-15 16:58
@alandroid so if I understood correctly `ndcDynamicComponent` will not work unless you apply `ndcDynamicInputs` ?

**Comment by alandroid** [comment] 2018-03-15 17:33
Not the case at all:
I had some leftover code from previous attempts to get a dynamic component - *ngComponentOutlet applied to the same element which was preventing correct render.

**Comment by gund** [comment] 2018-03-15 17:58
Great, I will close this issue than.

**Closed by gund** 2018-03-15 17:58 UTC
